#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestleBLL.EF_Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_Nestle2")]
	public partial class NestleDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_PersonelBilgileri(tbl_PersonelBilgileri instance);
    partial void Updatetbl_PersonelBilgileri(tbl_PersonelBilgileri instance);
    partial void Deletetbl_PersonelBilgileri(tbl_PersonelBilgileri instance);
    partial void Inserttbl_Departman(tbl_Departman instance);
    partial void Updatetbl_Departman(tbl_Departman instance);
    partial void Deletetbl_Departman(tbl_Departman instance);
    partial void Inserttbl_BasvuruForm(tbl_BasvuruForm instance);
    partial void Updatetbl_BasvuruForm(tbl_BasvuruForm instance);
    partial void Deletetbl_BasvuruForm(tbl_BasvuruForm instance);
    partial void Inserttbl_Depolama(tbl_Depolama instance);
    partial void Updatetbl_Depolama(tbl_Depolama instance);
    partial void Deletetbl_Depolama(tbl_Depolama instance);
    partial void Inserttbl_UrunBilgisi(tbl_UrunBilgisi instance);
    partial void Updatetbl_UrunBilgisi(tbl_UrunBilgisi instance);
    partial void Deletetbl_UrunBilgisi(tbl_UrunBilgisi instance);
    partial void Inserttbl_UrunTuru(tbl_UrunTuru instance);
    partial void Updatetbl_UrunTuru(tbl_UrunTuru instance);
    partial void Deletetbl_UrunTuru(tbl_UrunTuru instance);
    partial void Inserttbl_SatisDurumu(tbl_SatisDurumu instance);
    partial void Updatetbl_SatisDurumu(tbl_SatisDurumu instance);
    partial void Deletetbl_SatisDurumu(tbl_SatisDurumu instance);
    partial void Inserttbl_Satis(tbl_Satis instance);
    partial void Updatetbl_Satis(tbl_Satis instance);
    partial void Deletetbl_Satis(tbl_Satis instance);
    partial void Inserttbl_Teklif(tbl_Teklif instance);
    partial void Updatetbl_Teklif(tbl_Teklif instance);
    partial void Deletetbl_Teklif(tbl_Teklif instance);
    partial void Inserttbl_Sevkiyat(tbl_Sevkiyat instance);
    partial void Updatetbl_Sevkiyat(tbl_Sevkiyat instance);
    partial void Deletetbl_Sevkiyat(tbl_Sevkiyat instance);
    partial void Inserttbl_Lojistik(tbl_Lojistik instance);
    partial void Updatetbl_Lojistik(tbl_Lojistik instance);
    partial void Deletetbl_Lojistik(tbl_Lojistik instance);
    partial void Inserttbl_KullaniciBilgileri(tbl_KullaniciBilgileri instance);
    partial void Updatetbl_KullaniciBilgileri(tbl_KullaniciBilgileri instance);
    partial void Deletetbl_KullaniciBilgileri(tbl_KullaniciBilgileri instance);
    partial void Inserttbl_Kurumsal(tbl_Kurumsal instance);
    partial void Updatetbl_Kurumsal(tbl_Kurumsal instance);
    partial void Deletetbl_Kurumsal(tbl_Kurumsal instance);
    #endregion
		
		public NestleDataContext() : 
				base(global::NestleBLL.Properties.Settings.Default.db_Nestle2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NestleDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NestleDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NestleDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NestleDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_PersonelBilgileri> tbl_PersonelBilgileris
		{
			get
			{
				return this.GetTable<tbl_PersonelBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Departman> tbl_Departmans
		{
			get
			{
				return this.GetTable<tbl_Departman>();
			}
		}
		
		public System.Data.Linq.Table<tbl_BasvuruForm> tbl_BasvuruForms
		{
			get
			{
				return this.GetTable<tbl_BasvuruForm>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Depolama> tbl_Depolamas
		{
			get
			{
				return this.GetTable<tbl_Depolama>();
			}
		}
		
		public System.Data.Linq.Table<tbl_UrunBilgisi> tbl_UrunBilgisis
		{
			get
			{
				return this.GetTable<tbl_UrunBilgisi>();
			}
		}
		
		public System.Data.Linq.Table<tbl_UrunTuru> tbl_UrunTurus
		{
			get
			{
				return this.GetTable<tbl_UrunTuru>();
			}
		}
		
		public System.Data.Linq.Table<tbl_SatisDurumu> tbl_SatisDurumus
		{
			get
			{
				return this.GetTable<tbl_SatisDurumu>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Satis> tbl_Satis
		{
			get
			{
				return this.GetTable<tbl_Satis>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Teklif> tbl_Teklifs
		{
			get
			{
				return this.GetTable<tbl_Teklif>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Sevkiyat> tbl_Sevkiyats
		{
			get
			{
				return this.GetTable<tbl_Sevkiyat>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Lojistik> tbl_Lojistiks
		{
			get
			{
				return this.GetTable<tbl_Lojistik>();
			}
		}
		
		public System.Data.Linq.Table<tbl_KullaniciBilgileri> tbl_KullaniciBilgileris
		{
			get
			{
				return this.GetTable<tbl_KullaniciBilgileri>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Kurumsal> tbl_Kurumsals
		{
			get
			{
				return this.GetTable<tbl_Kurumsal>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_PersonelBilgileri")]
	public partial class tbl_PersonelBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _per_id;
		
		private string _perAdi;
		
		private string _perSoyadi;
		
		private System.DateTime _perDogumTarihi;
		
		private string _perTcno;
		
		private string _perUnvan;
		
		private string _perTelefon;
		
		private string _perAdres;
		
		private string _peril;
		
		private string _perilce;
		
		private string _perUlke;
		
		private int _departman_id;
		
		private string _perMail;
		
		private string _perResim;
		
		private EntityRef<tbl_Departman> _tbl_Departman;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onper_idChanging(int value);
    partial void Onper_idChanged();
    partial void OnperAdiChanging(string value);
    partial void OnperAdiChanged();
    partial void OnperSoyadiChanging(string value);
    partial void OnperSoyadiChanged();
    partial void OnperDogumTarihiChanging(System.DateTime value);
    partial void OnperDogumTarihiChanged();
    partial void OnperTcnoChanging(string value);
    partial void OnperTcnoChanged();
    partial void OnperUnvanChanging(string value);
    partial void OnperUnvanChanged();
    partial void OnperTelefonChanging(string value);
    partial void OnperTelefonChanged();
    partial void OnperAdresChanging(string value);
    partial void OnperAdresChanged();
    partial void OnperilChanging(string value);
    partial void OnperilChanged();
    partial void OnperilceChanging(string value);
    partial void OnperilceChanged();
    partial void OnperUlkeChanging(string value);
    partial void OnperUlkeChanged();
    partial void Ondepartman_idChanging(int value);
    partial void Ondepartman_idChanged();
    partial void OnperMailChanging(string value);
    partial void OnperMailChanged();
    partial void OnperResimChanging(string value);
    partial void OnperResimChanged();
    #endregion
		
		public tbl_PersonelBilgileri()
		{
			this._tbl_Departman = default(EntityRef<tbl_Departman>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int per_id
		{
			get
			{
				return this._per_id;
			}
			set
			{
				if ((this._per_id != value))
				{
					this.Onper_idChanging(value);
					this.SendPropertyChanging();
					this._per_id = value;
					this.SendPropertyChanged("per_id");
					this.Onper_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string perAdi
		{
			get
			{
				return this._perAdi;
			}
			set
			{
				if ((this._perAdi != value))
				{
					this.OnperAdiChanging(value);
					this.SendPropertyChanging();
					this._perAdi = value;
					this.SendPropertyChanged("perAdi");
					this.OnperAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perSoyadi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string perSoyadi
		{
			get
			{
				return this._perSoyadi;
			}
			set
			{
				if ((this._perSoyadi != value))
				{
					this.OnperSoyadiChanging(value);
					this.SendPropertyChanging();
					this._perSoyadi = value;
					this.SendPropertyChanged("perSoyadi");
					this.OnperSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perDogumTarihi", DbType="Date NOT NULL")]
		public System.DateTime perDogumTarihi
		{
			get
			{
				return this._perDogumTarihi;
			}
			set
			{
				if ((this._perDogumTarihi != value))
				{
					this.OnperDogumTarihiChanging(value);
					this.SendPropertyChanging();
					this._perDogumTarihi = value;
					this.SendPropertyChanged("perDogumTarihi");
					this.OnperDogumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perTcno", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string perTcno
		{
			get
			{
				return this._perTcno;
			}
			set
			{
				if ((this._perTcno != value))
				{
					this.OnperTcnoChanging(value);
					this.SendPropertyChanging();
					this._perTcno = value;
					this.SendPropertyChanged("perTcno");
					this.OnperTcnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perUnvan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string perUnvan
		{
			get
			{
				return this._perUnvan;
			}
			set
			{
				if ((this._perUnvan != value))
				{
					this.OnperUnvanChanging(value);
					this.SendPropertyChanging();
					this._perUnvan = value;
					this.SendPropertyChanged("perUnvan");
					this.OnperUnvanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perTelefon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string perTelefon
		{
			get
			{
				return this._perTelefon;
			}
			set
			{
				if ((this._perTelefon != value))
				{
					this.OnperTelefonChanging(value);
					this.SendPropertyChanging();
					this._perTelefon = value;
					this.SendPropertyChanged("perTelefon");
					this.OnperTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perAdres", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string perAdres
		{
			get
			{
				return this._perAdres;
			}
			set
			{
				if ((this._perAdres != value))
				{
					this.OnperAdresChanging(value);
					this.SendPropertyChanging();
					this._perAdres = value;
					this.SendPropertyChanged("perAdres");
					this.OnperAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_peril", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string peril
		{
			get
			{
				return this._peril;
			}
			set
			{
				if ((this._peril != value))
				{
					this.OnperilChanging(value);
					this.SendPropertyChanging();
					this._peril = value;
					this.SendPropertyChanged("peril");
					this.OnperilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perilce", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string perilce
		{
			get
			{
				return this._perilce;
			}
			set
			{
				if ((this._perilce != value))
				{
					this.OnperilceChanging(value);
					this.SendPropertyChanging();
					this._perilce = value;
					this.SendPropertyChanged("perilce");
					this.OnperilceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perUlke", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string perUlke
		{
			get
			{
				return this._perUlke;
			}
			set
			{
				if ((this._perUlke != value))
				{
					this.OnperUlkeChanging(value);
					this.SendPropertyChanging();
					this._perUlke = value;
					this.SendPropertyChanged("perUlke");
					this.OnperUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departman_id", DbType="Int NOT NULL")]
		public int departman_id
		{
			get
			{
				return this._departman_id;
			}
			set
			{
				if ((this._departman_id != value))
				{
					if (this._tbl_Departman.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondepartman_idChanging(value);
					this.SendPropertyChanging();
					this._departman_id = value;
					this.SendPropertyChanged("departman_id");
					this.Ondepartman_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perMail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string perMail
		{
			get
			{
				return this._perMail;
			}
			set
			{
				if ((this._perMail != value))
				{
					this.OnperMailChanging(value);
					this.SendPropertyChanging();
					this._perMail = value;
					this.SendPropertyChanged("perMail");
					this.OnperMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_perResim", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string perResim
		{
			get
			{
				return this._perResim;
			}
			set
			{
				if ((this._perResim != value))
				{
					this.OnperResimChanging(value);
					this.SendPropertyChanging();
					this._perResim = value;
					this.SendPropertyChanged("perResim");
					this.OnperResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Departman_tbl_PersonelBilgileri", Storage="_tbl_Departman", ThisKey="departman_id", OtherKey="departman_id", IsForeignKey=true)]
		public tbl_Departman tbl_Departman
		{
			get
			{
				return this._tbl_Departman.Entity;
			}
			set
			{
				tbl_Departman previousValue = this._tbl_Departman.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Departman.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Departman.Entity = null;
						previousValue.tbl_PersonelBilgileris.Remove(this);
					}
					this._tbl_Departman.Entity = value;
					if ((value != null))
					{
						value.tbl_PersonelBilgileris.Add(this);
						this._departman_id = value.departman_id;
					}
					else
					{
						this._departman_id = default(int);
					}
					this.SendPropertyChanged("tbl_Departman");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Departman")]
	public partial class tbl_Departman : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _departman_id;
		
		private string _departmanAdi;
		
		private EntitySet<tbl_PersonelBilgileri> _tbl_PersonelBilgileris;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondepartman_idChanging(int value);
    partial void Ondepartman_idChanged();
    partial void OndepartmanAdiChanging(string value);
    partial void OndepartmanAdiChanged();
    #endregion
		
		public tbl_Departman()
		{
			this._tbl_PersonelBilgileris = new EntitySet<tbl_PersonelBilgileri>(new Action<tbl_PersonelBilgileri>(this.attach_tbl_PersonelBilgileris), new Action<tbl_PersonelBilgileri>(this.detach_tbl_PersonelBilgileris));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departman_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int departman_id
		{
			get
			{
				return this._departman_id;
			}
			set
			{
				if ((this._departman_id != value))
				{
					this.Ondepartman_idChanging(value);
					this.SendPropertyChanging();
					this._departman_id = value;
					this.SendPropertyChanged("departman_id");
					this.Ondepartman_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departmanAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string departmanAdi
		{
			get
			{
				return this._departmanAdi;
			}
			set
			{
				if ((this._departmanAdi != value))
				{
					this.OndepartmanAdiChanging(value);
					this.SendPropertyChanging();
					this._departmanAdi = value;
					this.SendPropertyChanged("departmanAdi");
					this.OndepartmanAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Departman_tbl_PersonelBilgileri", Storage="_tbl_PersonelBilgileris", ThisKey="departman_id", OtherKey="departman_id")]
		public EntitySet<tbl_PersonelBilgileri> tbl_PersonelBilgileris
		{
			get
			{
				return this._tbl_PersonelBilgileris;
			}
			set
			{
				this._tbl_PersonelBilgileris.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_PersonelBilgileris(tbl_PersonelBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Departman = this;
		}
		
		private void detach_tbl_PersonelBilgileris(tbl_PersonelBilgileri entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Departman = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_BasvuruForm")]
	public partial class tbl_BasvuruForm : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _basvuru_id;
		
		private string _basvuruAdi;
		
		private string _basvuruSoyadi;
		
		private System.DateTime _basvuruDogumTarihi;
		
		private string _basvuruCinsiyet;
		
		private string _basvuruYabanciDil;
		
		private string _basvuruAskerlikDurumu;
		
		private string _basvuruMedeniDurum;
		
		private string _basvuruEgitim;
		
		private string _basvuruDeneyim;
		
		private string _basvuruAdres;
		
		private string _basvuruTelefon;
		
		private string _basvuruMail;
		
		private string _basvuruResim;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbasvuru_idChanging(int value);
    partial void Onbasvuru_idChanged();
    partial void OnbasvuruAdiChanging(string value);
    partial void OnbasvuruAdiChanged();
    partial void OnbasvuruSoyadiChanging(string value);
    partial void OnbasvuruSoyadiChanged();
    partial void OnbasvuruDogumTarihiChanging(System.DateTime value);
    partial void OnbasvuruDogumTarihiChanged();
    partial void OnbasvuruCinsiyetChanging(string value);
    partial void OnbasvuruCinsiyetChanged();
    partial void OnbasvuruYabanciDilChanging(string value);
    partial void OnbasvuruYabanciDilChanged();
    partial void OnbasvuruAskerlikDurumuChanging(string value);
    partial void OnbasvuruAskerlikDurumuChanged();
    partial void OnbasvuruMedeniDurumChanging(string value);
    partial void OnbasvuruMedeniDurumChanged();
    partial void OnbasvuruEgitimChanging(string value);
    partial void OnbasvuruEgitimChanged();
    partial void OnbasvuruDeneyimChanging(string value);
    partial void OnbasvuruDeneyimChanged();
    partial void OnbasvuruAdresChanging(string value);
    partial void OnbasvuruAdresChanged();
    partial void OnbasvuruTelefonChanging(string value);
    partial void OnbasvuruTelefonChanged();
    partial void OnbasvuruMailChanging(string value);
    partial void OnbasvuruMailChanged();
    partial void OnbasvuruResimChanging(string value);
    partial void OnbasvuruResimChanged();
    #endregion
		
		public tbl_BasvuruForm()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuru_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int basvuru_id
		{
			get
			{
				return this._basvuru_id;
			}
			set
			{
				if ((this._basvuru_id != value))
				{
					this.Onbasvuru_idChanging(value);
					this.SendPropertyChanging();
					this._basvuru_id = value;
					this.SendPropertyChanged("basvuru_id");
					this.Onbasvuru_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string basvuruAdi
		{
			get
			{
				return this._basvuruAdi;
			}
			set
			{
				if ((this._basvuruAdi != value))
				{
					this.OnbasvuruAdiChanging(value);
					this.SendPropertyChanging();
					this._basvuruAdi = value;
					this.SendPropertyChanged("basvuruAdi");
					this.OnbasvuruAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruSoyadi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string basvuruSoyadi
		{
			get
			{
				return this._basvuruSoyadi;
			}
			set
			{
				if ((this._basvuruSoyadi != value))
				{
					this.OnbasvuruSoyadiChanging(value);
					this.SendPropertyChanging();
					this._basvuruSoyadi = value;
					this.SendPropertyChanged("basvuruSoyadi");
					this.OnbasvuruSoyadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruDogumTarihi", DbType="Date NOT NULL")]
		public System.DateTime basvuruDogumTarihi
		{
			get
			{
				return this._basvuruDogumTarihi;
			}
			set
			{
				if ((this._basvuruDogumTarihi != value))
				{
					this.OnbasvuruDogumTarihiChanging(value);
					this.SendPropertyChanging();
					this._basvuruDogumTarihi = value;
					this.SendPropertyChanged("basvuruDogumTarihi");
					this.OnbasvuruDogumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruCinsiyet", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string basvuruCinsiyet
		{
			get
			{
				return this._basvuruCinsiyet;
			}
			set
			{
				if ((this._basvuruCinsiyet != value))
				{
					this.OnbasvuruCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._basvuruCinsiyet = value;
					this.SendPropertyChanged("basvuruCinsiyet");
					this.OnbasvuruCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruYabanciDil", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string basvuruYabanciDil
		{
			get
			{
				return this._basvuruYabanciDil;
			}
			set
			{
				if ((this._basvuruYabanciDil != value))
				{
					this.OnbasvuruYabanciDilChanging(value);
					this.SendPropertyChanging();
					this._basvuruYabanciDil = value;
					this.SendPropertyChanged("basvuruYabanciDil");
					this.OnbasvuruYabanciDilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruAskerlikDurumu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string basvuruAskerlikDurumu
		{
			get
			{
				return this._basvuruAskerlikDurumu;
			}
			set
			{
				if ((this._basvuruAskerlikDurumu != value))
				{
					this.OnbasvuruAskerlikDurumuChanging(value);
					this.SendPropertyChanging();
					this._basvuruAskerlikDurumu = value;
					this.SendPropertyChanged("basvuruAskerlikDurumu");
					this.OnbasvuruAskerlikDurumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruMedeniDurum", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string basvuruMedeniDurum
		{
			get
			{
				return this._basvuruMedeniDurum;
			}
			set
			{
				if ((this._basvuruMedeniDurum != value))
				{
					this.OnbasvuruMedeniDurumChanging(value);
					this.SendPropertyChanging();
					this._basvuruMedeniDurum = value;
					this.SendPropertyChanged("basvuruMedeniDurum");
					this.OnbasvuruMedeniDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruEgitim", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string basvuruEgitim
		{
			get
			{
				return this._basvuruEgitim;
			}
			set
			{
				if ((this._basvuruEgitim != value))
				{
					this.OnbasvuruEgitimChanging(value);
					this.SendPropertyChanging();
					this._basvuruEgitim = value;
					this.SendPropertyChanged("basvuruEgitim");
					this.OnbasvuruEgitimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruDeneyim", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string basvuruDeneyim
		{
			get
			{
				return this._basvuruDeneyim;
			}
			set
			{
				if ((this._basvuruDeneyim != value))
				{
					this.OnbasvuruDeneyimChanging(value);
					this.SendPropertyChanging();
					this._basvuruDeneyim = value;
					this.SendPropertyChanged("basvuruDeneyim");
					this.OnbasvuruDeneyimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruAdres", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string basvuruAdres
		{
			get
			{
				return this._basvuruAdres;
			}
			set
			{
				if ((this._basvuruAdres != value))
				{
					this.OnbasvuruAdresChanging(value);
					this.SendPropertyChanging();
					this._basvuruAdres = value;
					this.SendPropertyChanged("basvuruAdres");
					this.OnbasvuruAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruTelefon", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string basvuruTelefon
		{
			get
			{
				return this._basvuruTelefon;
			}
			set
			{
				if ((this._basvuruTelefon != value))
				{
					this.OnbasvuruTelefonChanging(value);
					this.SendPropertyChanging();
					this._basvuruTelefon = value;
					this.SendPropertyChanged("basvuruTelefon");
					this.OnbasvuruTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruMail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string basvuruMail
		{
			get
			{
				return this._basvuruMail;
			}
			set
			{
				if ((this._basvuruMail != value))
				{
					this.OnbasvuruMailChanging(value);
					this.SendPropertyChanging();
					this._basvuruMail = value;
					this.SendPropertyChanged("basvuruMail");
					this.OnbasvuruMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_basvuruResim", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string basvuruResim
		{
			get
			{
				return this._basvuruResim;
			}
			set
			{
				if ((this._basvuruResim != value))
				{
					this.OnbasvuruResimChanging(value);
					this.SendPropertyChanging();
					this._basvuruResim = value;
					this.SendPropertyChanged("basvuruResim");
					this.OnbasvuruResimChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Depolama")]
	public partial class tbl_Depolama : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _depo_id;
		
		private string _depoAdi;
		
		private string _depoAdres;
		
		private EntitySet<tbl_UrunBilgisi> _tbl_UrunBilgisis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondepo_idChanging(int value);
    partial void Ondepo_idChanged();
    partial void OndepoAdiChanging(string value);
    partial void OndepoAdiChanged();
    partial void OndepoAdresChanging(string value);
    partial void OndepoAdresChanged();
    #endregion
		
		public tbl_Depolama()
		{
			this._tbl_UrunBilgisis = new EntitySet<tbl_UrunBilgisi>(new Action<tbl_UrunBilgisi>(this.attach_tbl_UrunBilgisis), new Action<tbl_UrunBilgisi>(this.detach_tbl_UrunBilgisis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depo_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int depo_id
		{
			get
			{
				return this._depo_id;
			}
			set
			{
				if ((this._depo_id != value))
				{
					this.Ondepo_idChanging(value);
					this.SendPropertyChanging();
					this._depo_id = value;
					this.SendPropertyChanged("depo_id");
					this.Ondepo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depoAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string depoAdi
		{
			get
			{
				return this._depoAdi;
			}
			set
			{
				if ((this._depoAdi != value))
				{
					this.OndepoAdiChanging(value);
					this.SendPropertyChanging();
					this._depoAdi = value;
					this.SendPropertyChanged("depoAdi");
					this.OndepoAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depoAdres", DbType="NVarChar(250)")]
		public string depoAdres
		{
			get
			{
				return this._depoAdres;
			}
			set
			{
				if ((this._depoAdres != value))
				{
					this.OndepoAdresChanging(value);
					this.SendPropertyChanging();
					this._depoAdres = value;
					this.SendPropertyChanged("depoAdres");
					this.OndepoAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Depolama_tbl_UrunBilgisi", Storage="_tbl_UrunBilgisis", ThisKey="depo_id", OtherKey="depo_id")]
		public EntitySet<tbl_UrunBilgisi> tbl_UrunBilgisis
		{
			get
			{
				return this._tbl_UrunBilgisis;
			}
			set
			{
				this._tbl_UrunBilgisis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_UrunBilgisis(tbl_UrunBilgisi entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Depolama = this;
		}
		
		private void detach_tbl_UrunBilgisis(tbl_UrunBilgisi entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Depolama = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_UrunBilgisi")]
	public partial class tbl_UrunBilgisi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _urun_id;
		
		private string _urun_adi;
		
		private int _uruntur_id;
		
		private System.DateTime _urunUretimTarihi;
		
		private decimal _urunFiyati;
		
		private int _urunMiktari;
		
		private int _depo_id;
		
		private EntitySet<tbl_Satis> _tbl_Satis;
		
		private EntitySet<tbl_Teklif> _tbl_Teklifs;
		
		private EntitySet<tbl_Sevkiyat> _tbl_Sevkiyats;
		
		private EntityRef<tbl_Depolama> _tbl_Depolama;
		
		private EntityRef<tbl_UrunTuru> _tbl_UrunTuru;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onurun_idChanging(int value);
    partial void Onurun_idChanged();
    partial void Onurun_adiChanging(string value);
    partial void Onurun_adiChanged();
    partial void Onuruntur_idChanging(int value);
    partial void Onuruntur_idChanged();
    partial void OnurunUretimTarihiChanging(System.DateTime value);
    partial void OnurunUretimTarihiChanged();
    partial void OnurunFiyatiChanging(decimal value);
    partial void OnurunFiyatiChanged();
    partial void OnurunMiktariChanging(int value);
    partial void OnurunMiktariChanged();
    partial void Ondepo_idChanging(int value);
    partial void Ondepo_idChanged();
    #endregion
		
		public tbl_UrunBilgisi()
		{
			this._tbl_Satis = new EntitySet<tbl_Satis>(new Action<tbl_Satis>(this.attach_tbl_Satis), new Action<tbl_Satis>(this.detach_tbl_Satis));
			this._tbl_Teklifs = new EntitySet<tbl_Teklif>(new Action<tbl_Teklif>(this.attach_tbl_Teklifs), new Action<tbl_Teklif>(this.detach_tbl_Teklifs));
			this._tbl_Sevkiyats = new EntitySet<tbl_Sevkiyat>(new Action<tbl_Sevkiyat>(this.attach_tbl_Sevkiyats), new Action<tbl_Sevkiyat>(this.detach_tbl_Sevkiyats));
			this._tbl_Depolama = default(EntityRef<tbl_Depolama>);
			this._tbl_UrunTuru = default(EntityRef<tbl_UrunTuru>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urun_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int urun_id
		{
			get
			{
				return this._urun_id;
			}
			set
			{
				if ((this._urun_id != value))
				{
					this.Onurun_idChanging(value);
					this.SendPropertyChanging();
					this._urun_id = value;
					this.SendPropertyChanged("urun_id");
					this.Onurun_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urun_adi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string urun_adi
		{
			get
			{
				return this._urun_adi;
			}
			set
			{
				if ((this._urun_adi != value))
				{
					this.Onurun_adiChanging(value);
					this.SendPropertyChanging();
					this._urun_adi = value;
					this.SendPropertyChanged("urun_adi");
					this.Onurun_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uruntur_id", DbType="Int NOT NULL")]
		public int uruntur_id
		{
			get
			{
				return this._uruntur_id;
			}
			set
			{
				if ((this._uruntur_id != value))
				{
					if (this._tbl_UrunTuru.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuruntur_idChanging(value);
					this.SendPropertyChanging();
					this._uruntur_id = value;
					this.SendPropertyChanged("uruntur_id");
					this.Onuruntur_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunUretimTarihi", DbType="Date NOT NULL")]
		public System.DateTime urunUretimTarihi
		{
			get
			{
				return this._urunUretimTarihi;
			}
			set
			{
				if ((this._urunUretimTarihi != value))
				{
					this.OnurunUretimTarihiChanging(value);
					this.SendPropertyChanging();
					this._urunUretimTarihi = value;
					this.SendPropertyChanged("urunUretimTarihi");
					this.OnurunUretimTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunFiyati", DbType="Money NOT NULL")]
		public decimal urunFiyati
		{
			get
			{
				return this._urunFiyati;
			}
			set
			{
				if ((this._urunFiyati != value))
				{
					this.OnurunFiyatiChanging(value);
					this.SendPropertyChanging();
					this._urunFiyati = value;
					this.SendPropertyChanged("urunFiyati");
					this.OnurunFiyatiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunMiktari", DbType="Int NOT NULL")]
		public int urunMiktari
		{
			get
			{
				return this._urunMiktari;
			}
			set
			{
				if ((this._urunMiktari != value))
				{
					this.OnurunMiktariChanging(value);
					this.SendPropertyChanging();
					this._urunMiktari = value;
					this.SendPropertyChanged("urunMiktari");
					this.OnurunMiktariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_depo_id", DbType="Int NOT NULL")]
		public int depo_id
		{
			get
			{
				return this._depo_id;
			}
			set
			{
				if ((this._depo_id != value))
				{
					if (this._tbl_Depolama.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondepo_idChanging(value);
					this.SendPropertyChanging();
					this._depo_id = value;
					this.SendPropertyChanged("depo_id");
					this.Ondepo_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_UrunBilgisi_tbl_Satis", Storage="_tbl_Satis", ThisKey="urun_id", OtherKey="urun_id")]
		public EntitySet<tbl_Satis> tbl_Satis
		{
			get
			{
				return this._tbl_Satis;
			}
			set
			{
				this._tbl_Satis.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_UrunBilgisi_tbl_Teklif", Storage="_tbl_Teklifs", ThisKey="urun_id", OtherKey="urun_id")]
		public EntitySet<tbl_Teklif> tbl_Teklifs
		{
			get
			{
				return this._tbl_Teklifs;
			}
			set
			{
				this._tbl_Teklifs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_UrunBilgisi_tbl_Sevkiyat", Storage="_tbl_Sevkiyats", ThisKey="urun_id", OtherKey="urun_id")]
		public EntitySet<tbl_Sevkiyat> tbl_Sevkiyats
		{
			get
			{
				return this._tbl_Sevkiyats;
			}
			set
			{
				this._tbl_Sevkiyats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Depolama_tbl_UrunBilgisi", Storage="_tbl_Depolama", ThisKey="depo_id", OtherKey="depo_id", IsForeignKey=true)]
		public tbl_Depolama tbl_Depolama
		{
			get
			{
				return this._tbl_Depolama.Entity;
			}
			set
			{
				tbl_Depolama previousValue = this._tbl_Depolama.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Depolama.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Depolama.Entity = null;
						previousValue.tbl_UrunBilgisis.Remove(this);
					}
					this._tbl_Depolama.Entity = value;
					if ((value != null))
					{
						value.tbl_UrunBilgisis.Add(this);
						this._depo_id = value.depo_id;
					}
					else
					{
						this._depo_id = default(int);
					}
					this.SendPropertyChanged("tbl_Depolama");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_UrunTuru_tbl_UrunBilgisi", Storage="_tbl_UrunTuru", ThisKey="uruntur_id", OtherKey="uruntur_id", IsForeignKey=true)]
		public tbl_UrunTuru tbl_UrunTuru
		{
			get
			{
				return this._tbl_UrunTuru.Entity;
			}
			set
			{
				tbl_UrunTuru previousValue = this._tbl_UrunTuru.Entity;
				if (((previousValue != value) 
							|| (this._tbl_UrunTuru.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_UrunTuru.Entity = null;
						previousValue.tbl_UrunBilgisis.Remove(this);
					}
					this._tbl_UrunTuru.Entity = value;
					if ((value != null))
					{
						value.tbl_UrunBilgisis.Add(this);
						this._uruntur_id = value.uruntur_id;
					}
					else
					{
						this._uruntur_id = default(int);
					}
					this.SendPropertyChanged("tbl_UrunTuru");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Satis(tbl_Satis entity)
		{
			this.SendPropertyChanging();
			entity.tbl_UrunBilgisi = this;
		}
		
		private void detach_tbl_Satis(tbl_Satis entity)
		{
			this.SendPropertyChanging();
			entity.tbl_UrunBilgisi = null;
		}
		
		private void attach_tbl_Teklifs(tbl_Teklif entity)
		{
			this.SendPropertyChanging();
			entity.tbl_UrunBilgisi = this;
		}
		
		private void detach_tbl_Teklifs(tbl_Teklif entity)
		{
			this.SendPropertyChanging();
			entity.tbl_UrunBilgisi = null;
		}
		
		private void attach_tbl_Sevkiyats(tbl_Sevkiyat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_UrunBilgisi = this;
		}
		
		private void detach_tbl_Sevkiyats(tbl_Sevkiyat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_UrunBilgisi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_UrunTuru")]
	public partial class tbl_UrunTuru : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _uruntur_id;
		
		private string _uruntur_adi;
		
		private EntitySet<tbl_UrunBilgisi> _tbl_UrunBilgisis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuruntur_idChanging(int value);
    partial void Onuruntur_idChanged();
    partial void Onuruntur_adiChanging(string value);
    partial void Onuruntur_adiChanged();
    #endregion
		
		public tbl_UrunTuru()
		{
			this._tbl_UrunBilgisis = new EntitySet<tbl_UrunBilgisi>(new Action<tbl_UrunBilgisi>(this.attach_tbl_UrunBilgisis), new Action<tbl_UrunBilgisi>(this.detach_tbl_UrunBilgisis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uruntur_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int uruntur_id
		{
			get
			{
				return this._uruntur_id;
			}
			set
			{
				if ((this._uruntur_id != value))
				{
					this.Onuruntur_idChanging(value);
					this.SendPropertyChanging();
					this._uruntur_id = value;
					this.SendPropertyChanged("uruntur_id");
					this.Onuruntur_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uruntur_adi", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string uruntur_adi
		{
			get
			{
				return this._uruntur_adi;
			}
			set
			{
				if ((this._uruntur_adi != value))
				{
					this.Onuruntur_adiChanging(value);
					this.SendPropertyChanging();
					this._uruntur_adi = value;
					this.SendPropertyChanged("uruntur_adi");
					this.Onuruntur_adiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_UrunTuru_tbl_UrunBilgisi", Storage="_tbl_UrunBilgisis", ThisKey="uruntur_id", OtherKey="uruntur_id")]
		public EntitySet<tbl_UrunBilgisi> tbl_UrunBilgisis
		{
			get
			{
				return this._tbl_UrunBilgisis;
			}
			set
			{
				this._tbl_UrunBilgisis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_UrunBilgisis(tbl_UrunBilgisi entity)
		{
			this.SendPropertyChanging();
			entity.tbl_UrunTuru = this;
		}
		
		private void detach_tbl_UrunBilgisis(tbl_UrunBilgisi entity)
		{
			this.SendPropertyChanging();
			entity.tbl_UrunTuru = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_SatisDurumu")]
	public partial class tbl_SatisDurumu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _satisDurumu_id;
		
		private string _satisDurumu;
		
		private EntitySet<tbl_Satis> _tbl_Satis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsatisDurumu_idChanging(int value);
    partial void OnsatisDurumu_idChanged();
    partial void OnsatisDurumuChanging(string value);
    partial void OnsatisDurumuChanged();
    #endregion
		
		public tbl_SatisDurumu()
		{
			this._tbl_Satis = new EntitySet<tbl_Satis>(new Action<tbl_Satis>(this.attach_tbl_Satis), new Action<tbl_Satis>(this.detach_tbl_Satis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_satisDurumu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int satisDurumu_id
		{
			get
			{
				return this._satisDurumu_id;
			}
			set
			{
				if ((this._satisDurumu_id != value))
				{
					this.OnsatisDurumu_idChanging(value);
					this.SendPropertyChanging();
					this._satisDurumu_id = value;
					this.SendPropertyChanged("satisDurumu_id");
					this.OnsatisDurumu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_satisDurumu", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string satisDurumu
		{
			get
			{
				return this._satisDurumu;
			}
			set
			{
				if ((this._satisDurumu != value))
				{
					this.OnsatisDurumuChanging(value);
					this.SendPropertyChanging();
					this._satisDurumu = value;
					this.SendPropertyChanged("satisDurumu");
					this.OnsatisDurumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_SatisDurumu_tbl_Satis", Storage="_tbl_Satis", ThisKey="satisDurumu_id", OtherKey="satisDurumu_id")]
		public EntitySet<tbl_Satis> tbl_Satis
		{
			get
			{
				return this._tbl_Satis;
			}
			set
			{
				this._tbl_Satis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Satis(tbl_Satis entity)
		{
			this.SendPropertyChanging();
			entity.tbl_SatisDurumu = this;
		}
		
		private void detach_tbl_Satis(tbl_Satis entity)
		{
			this.SendPropertyChanging();
			entity.tbl_SatisDurumu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Satis")]
	public partial class tbl_Satis : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _satis_id;
		
		private string _FirmaAdi;
		
		private System.DateTime _SatisTarihi;
		
		private string _TeslimAdresi;
		
		private string _TeslimSehir;
		
		private string _TeslimUlke;
		
		private System.DateTime _TeslimTarihi;
		
		private int _urun_id;
		
		private int _satAdet;
		
		private int _satisDurumu_id;
		
		private System.Nullable<decimal> _SatisTutari;
		
		private EntitySet<tbl_Sevkiyat> _tbl_Sevkiyats;
		
		private EntityRef<tbl_SatisDurumu> _tbl_SatisDurumu;
		
		private EntityRef<tbl_UrunBilgisi> _tbl_UrunBilgisi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsatis_idChanging(int value);
    partial void Onsatis_idChanged();
    partial void OnFirmaAdiChanging(string value);
    partial void OnFirmaAdiChanged();
    partial void OnSatisTarihiChanging(System.DateTime value);
    partial void OnSatisTarihiChanged();
    partial void OnTeslimAdresiChanging(string value);
    partial void OnTeslimAdresiChanged();
    partial void OnTeslimSehirChanging(string value);
    partial void OnTeslimSehirChanged();
    partial void OnTeslimUlkeChanging(string value);
    partial void OnTeslimUlkeChanged();
    partial void OnTeslimTarihiChanging(System.DateTime value);
    partial void OnTeslimTarihiChanged();
    partial void Onurun_idChanging(int value);
    partial void Onurun_idChanged();
    partial void OnsatAdetChanging(int value);
    partial void OnsatAdetChanged();
    partial void OnsatisDurumu_idChanging(int value);
    partial void OnsatisDurumu_idChanged();
    partial void OnSatisTutariChanging(System.Nullable<decimal> value);
    partial void OnSatisTutariChanged();
    #endregion
		
		public tbl_Satis()
		{
			this._tbl_Sevkiyats = new EntitySet<tbl_Sevkiyat>(new Action<tbl_Sevkiyat>(this.attach_tbl_Sevkiyats), new Action<tbl_Sevkiyat>(this.detach_tbl_Sevkiyats));
			this._tbl_SatisDurumu = default(EntityRef<tbl_SatisDurumu>);
			this._tbl_UrunBilgisi = default(EntityRef<tbl_UrunBilgisi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_satis_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int satis_id
		{
			get
			{
				return this._satis_id;
			}
			set
			{
				if ((this._satis_id != value))
				{
					this.Onsatis_idChanging(value);
					this.SendPropertyChanging();
					this._satis_id = value;
					this.SendPropertyChanged("satis_id");
					this.Onsatis_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirmaAdi", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string FirmaAdi
		{
			get
			{
				return this._FirmaAdi;
			}
			set
			{
				if ((this._FirmaAdi != value))
				{
					this.OnFirmaAdiChanging(value);
					this.SendPropertyChanging();
					this._FirmaAdi = value;
					this.SendPropertyChanged("FirmaAdi");
					this.OnFirmaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisTarihi", DbType="Date NOT NULL")]
		public System.DateTime SatisTarihi
		{
			get
			{
				return this._SatisTarihi;
			}
			set
			{
				if ((this._SatisTarihi != value))
				{
					this.OnSatisTarihiChanging(value);
					this.SendPropertyChanging();
					this._SatisTarihi = value;
					this.SendPropertyChanged("SatisTarihi");
					this.OnSatisTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeslimAdresi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TeslimAdresi
		{
			get
			{
				return this._TeslimAdresi;
			}
			set
			{
				if ((this._TeslimAdresi != value))
				{
					this.OnTeslimAdresiChanging(value);
					this.SendPropertyChanging();
					this._TeslimAdresi = value;
					this.SendPropertyChanged("TeslimAdresi");
					this.OnTeslimAdresiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeslimSehir", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TeslimSehir
		{
			get
			{
				return this._TeslimSehir;
			}
			set
			{
				if ((this._TeslimSehir != value))
				{
					this.OnTeslimSehirChanging(value);
					this.SendPropertyChanging();
					this._TeslimSehir = value;
					this.SendPropertyChanged("TeslimSehir");
					this.OnTeslimSehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeslimUlke", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string TeslimUlke
		{
			get
			{
				return this._TeslimUlke;
			}
			set
			{
				if ((this._TeslimUlke != value))
				{
					this.OnTeslimUlkeChanging(value);
					this.SendPropertyChanging();
					this._TeslimUlke = value;
					this.SendPropertyChanged("TeslimUlke");
					this.OnTeslimUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeslimTarihi", DbType="Date NOT NULL")]
		public System.DateTime TeslimTarihi
		{
			get
			{
				return this._TeslimTarihi;
			}
			set
			{
				if ((this._TeslimTarihi != value))
				{
					this.OnTeslimTarihiChanging(value);
					this.SendPropertyChanging();
					this._TeslimTarihi = value;
					this.SendPropertyChanged("TeslimTarihi");
					this.OnTeslimTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urun_id", DbType="Int NOT NULL")]
		public int urun_id
		{
			get
			{
				return this._urun_id;
			}
			set
			{
				if ((this._urun_id != value))
				{
					if (this._tbl_UrunBilgisi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onurun_idChanging(value);
					this.SendPropertyChanging();
					this._urun_id = value;
					this.SendPropertyChanged("urun_id");
					this.Onurun_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_satAdet", DbType="Int NOT NULL")]
		public int satAdet
		{
			get
			{
				return this._satAdet;
			}
			set
			{
				if ((this._satAdet != value))
				{
					this.OnsatAdetChanging(value);
					this.SendPropertyChanging();
					this._satAdet = value;
					this.SendPropertyChanged("satAdet");
					this.OnsatAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_satisDurumu_id", DbType="Int NOT NULL")]
		public int satisDurumu_id
		{
			get
			{
				return this._satisDurumu_id;
			}
			set
			{
				if ((this._satisDurumu_id != value))
				{
					if (this._tbl_SatisDurumu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnsatisDurumu_idChanging(value);
					this.SendPropertyChanging();
					this._satisDurumu_id = value;
					this.SendPropertyChanged("satisDurumu_id");
					this.OnsatisDurumu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatisTutari", DbType="Money")]
		public System.Nullable<decimal> SatisTutari
		{
			get
			{
				return this._SatisTutari;
			}
			set
			{
				if ((this._SatisTutari != value))
				{
					this.OnSatisTutariChanging(value);
					this.SendPropertyChanging();
					this._SatisTutari = value;
					this.SendPropertyChanged("SatisTutari");
					this.OnSatisTutariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Satis_tbl_Sevkiyat", Storage="_tbl_Sevkiyats", ThisKey="satis_id", OtherKey="satis_id")]
		public EntitySet<tbl_Sevkiyat> tbl_Sevkiyats
		{
			get
			{
				return this._tbl_Sevkiyats;
			}
			set
			{
				this._tbl_Sevkiyats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_SatisDurumu_tbl_Satis", Storage="_tbl_SatisDurumu", ThisKey="satisDurumu_id", OtherKey="satisDurumu_id", IsForeignKey=true)]
		public tbl_SatisDurumu tbl_SatisDurumu
		{
			get
			{
				return this._tbl_SatisDurumu.Entity;
			}
			set
			{
				tbl_SatisDurumu previousValue = this._tbl_SatisDurumu.Entity;
				if (((previousValue != value) 
							|| (this._tbl_SatisDurumu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_SatisDurumu.Entity = null;
						previousValue.tbl_Satis.Remove(this);
					}
					this._tbl_SatisDurumu.Entity = value;
					if ((value != null))
					{
						value.tbl_Satis.Add(this);
						this._satisDurumu_id = value.satisDurumu_id;
					}
					else
					{
						this._satisDurumu_id = default(int);
					}
					this.SendPropertyChanged("tbl_SatisDurumu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_UrunBilgisi_tbl_Satis", Storage="_tbl_UrunBilgisi", ThisKey="urun_id", OtherKey="urun_id", IsForeignKey=true)]
		public tbl_UrunBilgisi tbl_UrunBilgisi
		{
			get
			{
				return this._tbl_UrunBilgisi.Entity;
			}
			set
			{
				tbl_UrunBilgisi previousValue = this._tbl_UrunBilgisi.Entity;
				if (((previousValue != value) 
							|| (this._tbl_UrunBilgisi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_UrunBilgisi.Entity = null;
						previousValue.tbl_Satis.Remove(this);
					}
					this._tbl_UrunBilgisi.Entity = value;
					if ((value != null))
					{
						value.tbl_Satis.Add(this);
						this._urun_id = value.urun_id;
					}
					else
					{
						this._urun_id = default(int);
					}
					this.SendPropertyChanged("tbl_UrunBilgisi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Sevkiyats(tbl_Sevkiyat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Satis = this;
		}
		
		private void detach_tbl_Sevkiyats(tbl_Sevkiyat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Satis = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Teklif")]
	public partial class tbl_Teklif : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _teklif_id;
		
		private string _teklifNo;
		
		private string _tekFirmaAdi;
		
		private int _urun_id;
		
		private int _tekUrunMiktar;
		
		private decimal _teklifTutar;
		
		private EntityRef<tbl_UrunBilgisi> _tbl_UrunBilgisi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onteklif_idChanging(int value);
    partial void Onteklif_idChanged();
    partial void OnteklifNoChanging(string value);
    partial void OnteklifNoChanged();
    partial void OntekFirmaAdiChanging(string value);
    partial void OntekFirmaAdiChanged();
    partial void Onurun_idChanging(int value);
    partial void Onurun_idChanged();
    partial void OntekUrunMiktarChanging(int value);
    partial void OntekUrunMiktarChanged();
    partial void OnteklifTutarChanging(decimal value);
    partial void OnteklifTutarChanged();
    #endregion
		
		public tbl_Teklif()
		{
			this._tbl_UrunBilgisi = default(EntityRef<tbl_UrunBilgisi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teklif_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int teklif_id
		{
			get
			{
				return this._teklif_id;
			}
			set
			{
				if ((this._teklif_id != value))
				{
					this.Onteklif_idChanging(value);
					this.SendPropertyChanging();
					this._teklif_id = value;
					this.SendPropertyChanged("teklif_id");
					this.Onteklif_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teklifNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string teklifNo
		{
			get
			{
				return this._teklifNo;
			}
			set
			{
				if ((this._teklifNo != value))
				{
					this.OnteklifNoChanging(value);
					this.SendPropertyChanging();
					this._teklifNo = value;
					this.SendPropertyChanged("teklifNo");
					this.OnteklifNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tekFirmaAdi", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tekFirmaAdi
		{
			get
			{
				return this._tekFirmaAdi;
			}
			set
			{
				if ((this._tekFirmaAdi != value))
				{
					this.OntekFirmaAdiChanging(value);
					this.SendPropertyChanging();
					this._tekFirmaAdi = value;
					this.SendPropertyChanged("tekFirmaAdi");
					this.OntekFirmaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urun_id", DbType="Int NOT NULL")]
		public int urun_id
		{
			get
			{
				return this._urun_id;
			}
			set
			{
				if ((this._urun_id != value))
				{
					if (this._tbl_UrunBilgisi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onurun_idChanging(value);
					this.SendPropertyChanging();
					this._urun_id = value;
					this.SendPropertyChanged("urun_id");
					this.Onurun_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tekUrunMiktar", DbType="Int NOT NULL")]
		public int tekUrunMiktar
		{
			get
			{
				return this._tekUrunMiktar;
			}
			set
			{
				if ((this._tekUrunMiktar != value))
				{
					this.OntekUrunMiktarChanging(value);
					this.SendPropertyChanging();
					this._tekUrunMiktar = value;
					this.SendPropertyChanged("tekUrunMiktar");
					this.OntekUrunMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teklifTutar", DbType="Money NOT NULL")]
		public decimal teklifTutar
		{
			get
			{
				return this._teklifTutar;
			}
			set
			{
				if ((this._teklifTutar != value))
				{
					this.OnteklifTutarChanging(value);
					this.SendPropertyChanging();
					this._teklifTutar = value;
					this.SendPropertyChanged("teklifTutar");
					this.OnteklifTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_UrunBilgisi_tbl_Teklif", Storage="_tbl_UrunBilgisi", ThisKey="urun_id", OtherKey="urun_id", IsForeignKey=true)]
		public tbl_UrunBilgisi tbl_UrunBilgisi
		{
			get
			{
				return this._tbl_UrunBilgisi.Entity;
			}
			set
			{
				tbl_UrunBilgisi previousValue = this._tbl_UrunBilgisi.Entity;
				if (((previousValue != value) 
							|| (this._tbl_UrunBilgisi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_UrunBilgisi.Entity = null;
						previousValue.tbl_Teklifs.Remove(this);
					}
					this._tbl_UrunBilgisi.Entity = value;
					if ((value != null))
					{
						value.tbl_Teklifs.Add(this);
						this._urun_id = value.urun_id;
					}
					else
					{
						this._urun_id = default(int);
					}
					this.SendPropertyChanged("tbl_UrunBilgisi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Sevkiyat")]
	public partial class tbl_Sevkiyat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sev_id;
		
		private int _satis_id;
		
		private int _lojistik_id;
		
		private int _urun_id;
		
		private string _sevAdres;
		
		private EntityRef<tbl_Satis> _tbl_Satis;
		
		private EntityRef<tbl_UrunBilgisi> _tbl_UrunBilgisi;
		
		private EntityRef<tbl_Lojistik> _tbl_Lojistik;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsev_idChanging(int value);
    partial void Onsev_idChanged();
    partial void Onsatis_idChanging(int value);
    partial void Onsatis_idChanged();
    partial void Onlojistik_idChanging(int value);
    partial void Onlojistik_idChanged();
    partial void Onurun_idChanging(int value);
    partial void Onurun_idChanged();
    partial void OnsevAdresChanging(string value);
    partial void OnsevAdresChanged();
    #endregion
		
		public tbl_Sevkiyat()
		{
			this._tbl_Satis = default(EntityRef<tbl_Satis>);
			this._tbl_UrunBilgisi = default(EntityRef<tbl_UrunBilgisi>);
			this._tbl_Lojistik = default(EntityRef<tbl_Lojistik>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sev_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sev_id
		{
			get
			{
				return this._sev_id;
			}
			set
			{
				if ((this._sev_id != value))
				{
					this.Onsev_idChanging(value);
					this.SendPropertyChanging();
					this._sev_id = value;
					this.SendPropertyChanged("sev_id");
					this.Onsev_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_satis_id", DbType="Int NOT NULL")]
		public int satis_id
		{
			get
			{
				return this._satis_id;
			}
			set
			{
				if ((this._satis_id != value))
				{
					if (this._tbl_Satis.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsatis_idChanging(value);
					this.SendPropertyChanging();
					this._satis_id = value;
					this.SendPropertyChanged("satis_id");
					this.Onsatis_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lojistik_id", DbType="Int NOT NULL")]
		public int lojistik_id
		{
			get
			{
				return this._lojistik_id;
			}
			set
			{
				if ((this._lojistik_id != value))
				{
					if (this._tbl_Lojistik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onlojistik_idChanging(value);
					this.SendPropertyChanging();
					this._lojistik_id = value;
					this.SendPropertyChanged("lojistik_id");
					this.Onlojistik_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urun_id", DbType="Int NOT NULL")]
		public int urun_id
		{
			get
			{
				return this._urun_id;
			}
			set
			{
				if ((this._urun_id != value))
				{
					if (this._tbl_UrunBilgisi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onurun_idChanging(value);
					this.SendPropertyChanging();
					this._urun_id = value;
					this.SendPropertyChanged("urun_id");
					this.Onurun_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sevAdres", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string sevAdres
		{
			get
			{
				return this._sevAdres;
			}
			set
			{
				if ((this._sevAdres != value))
				{
					this.OnsevAdresChanging(value);
					this.SendPropertyChanging();
					this._sevAdres = value;
					this.SendPropertyChanged("sevAdres");
					this.OnsevAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Satis_tbl_Sevkiyat", Storage="_tbl_Satis", ThisKey="satis_id", OtherKey="satis_id", IsForeignKey=true)]
		public tbl_Satis tbl_Satis
		{
			get
			{
				return this._tbl_Satis.Entity;
			}
			set
			{
				tbl_Satis previousValue = this._tbl_Satis.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Satis.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Satis.Entity = null;
						previousValue.tbl_Sevkiyats.Remove(this);
					}
					this._tbl_Satis.Entity = value;
					if ((value != null))
					{
						value.tbl_Sevkiyats.Add(this);
						this._satis_id = value.satis_id;
					}
					else
					{
						this._satis_id = default(int);
					}
					this.SendPropertyChanged("tbl_Satis");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_UrunBilgisi_tbl_Sevkiyat", Storage="_tbl_UrunBilgisi", ThisKey="urun_id", OtherKey="urun_id", IsForeignKey=true)]
		public tbl_UrunBilgisi tbl_UrunBilgisi
		{
			get
			{
				return this._tbl_UrunBilgisi.Entity;
			}
			set
			{
				tbl_UrunBilgisi previousValue = this._tbl_UrunBilgisi.Entity;
				if (((previousValue != value) 
							|| (this._tbl_UrunBilgisi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_UrunBilgisi.Entity = null;
						previousValue.tbl_Sevkiyats.Remove(this);
					}
					this._tbl_UrunBilgisi.Entity = value;
					if ((value != null))
					{
						value.tbl_Sevkiyats.Add(this);
						this._urun_id = value.urun_id;
					}
					else
					{
						this._urun_id = default(int);
					}
					this.SendPropertyChanged("tbl_UrunBilgisi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Lojistik_tbl_Sevkiyat", Storage="_tbl_Lojistik", ThisKey="lojistik_id", OtherKey="lojistik_id", IsForeignKey=true)]
		public tbl_Lojistik tbl_Lojistik
		{
			get
			{
				return this._tbl_Lojistik.Entity;
			}
			set
			{
				tbl_Lojistik previousValue = this._tbl_Lojistik.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Lojistik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Lojistik.Entity = null;
						previousValue.tbl_Sevkiyats.Remove(this);
					}
					this._tbl_Lojistik.Entity = value;
					if ((value != null))
					{
						value.tbl_Sevkiyats.Add(this);
						this._lojistik_id = value.lojistik_id;
					}
					else
					{
						this._lojistik_id = default(int);
					}
					this.SendPropertyChanged("tbl_Lojistik");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Lojistik")]
	public partial class tbl_Lojistik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _lojistik_id;
		
		private string _lojistikTuru;
		
		private EntitySet<tbl_Sevkiyat> _tbl_Sevkiyats;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlojistik_idChanging(int value);
    partial void Onlojistik_idChanged();
    partial void OnlojistikTuruChanging(string value);
    partial void OnlojistikTuruChanged();
    #endregion
		
		public tbl_Lojistik()
		{
			this._tbl_Sevkiyats = new EntitySet<tbl_Sevkiyat>(new Action<tbl_Sevkiyat>(this.attach_tbl_Sevkiyats), new Action<tbl_Sevkiyat>(this.detach_tbl_Sevkiyats));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lojistik_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int lojistik_id
		{
			get
			{
				return this._lojistik_id;
			}
			set
			{
				if ((this._lojistik_id != value))
				{
					this.Onlojistik_idChanging(value);
					this.SendPropertyChanging();
					this._lojistik_id = value;
					this.SendPropertyChanged("lojistik_id");
					this.Onlojistik_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lojistikTuru", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string lojistikTuru
		{
			get
			{
				return this._lojistikTuru;
			}
			set
			{
				if ((this._lojistikTuru != value))
				{
					this.OnlojistikTuruChanging(value);
					this.SendPropertyChanging();
					this._lojistikTuru = value;
					this.SendPropertyChanged("lojistikTuru");
					this.OnlojistikTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Lojistik_tbl_Sevkiyat", Storage="_tbl_Sevkiyats", ThisKey="lojistik_id", OtherKey="lojistik_id")]
		public EntitySet<tbl_Sevkiyat> tbl_Sevkiyats
		{
			get
			{
				return this._tbl_Sevkiyats;
			}
			set
			{
				this._tbl_Sevkiyats.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Sevkiyats(tbl_Sevkiyat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Lojistik = this;
		}
		
		private void detach_tbl_Sevkiyats(tbl_Sevkiyat entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Lojistik = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_KullaniciBilgileri")]
	public partial class tbl_KullaniciBilgileri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kullaniciId;
		
		private string _kullaniciAdi;
		
		private string _sifre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkullaniciIdChanging(int value);
    partial void OnkullaniciIdChanged();
    partial void OnkullaniciAdiChanging(string value);
    partial void OnkullaniciAdiChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    #endregion
		
		public tbl_KullaniciBilgileri()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullaniciId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kullaniciId
		{
			get
			{
				return this._kullaniciId;
			}
			set
			{
				if ((this._kullaniciId != value))
				{
					this.OnkullaniciIdChanging(value);
					this.SendPropertyChanging();
					this._kullaniciId = value;
					this.SendPropertyChanged("kullaniciId");
					this.OnkullaniciIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullaniciAdi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string kullaniciAdi
		{
			get
			{
				return this._kullaniciAdi;
			}
			set
			{
				if ((this._kullaniciAdi != value))
				{
					this.OnkullaniciAdiChanging(value);
					this.SendPropertyChanging();
					this._kullaniciAdi = value;
					this.SendPropertyChanged("kullaniciAdi");
					this.OnkullaniciAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Kurumsal")]
	public partial class tbl_Kurumsal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kurumsal_id;
		
		private string _hakkinda;
		
		private string _slogan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkurumsal_idChanging(int value);
    partial void Onkurumsal_idChanged();
    partial void OnhakkindaChanging(string value);
    partial void OnhakkindaChanged();
    partial void OnsloganChanging(string value);
    partial void OnsloganChanged();
    #endregion
		
		public tbl_Kurumsal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kurumsal_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kurumsal_id
		{
			get
			{
				return this._kurumsal_id;
			}
			set
			{
				if ((this._kurumsal_id != value))
				{
					this.Onkurumsal_idChanging(value);
					this.SendPropertyChanging();
					this._kurumsal_id = value;
					this.SendPropertyChanged("kurumsal_id");
					this.Onkurumsal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hakkinda", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string hakkinda
		{
			get
			{
				return this._hakkinda;
			}
			set
			{
				if ((this._hakkinda != value))
				{
					this.OnhakkindaChanging(value);
					this.SendPropertyChanging();
					this._hakkinda = value;
					this.SendPropertyChanged("hakkinda");
					this.OnhakkindaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slogan", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string slogan
		{
			get
			{
				return this._slogan;
			}
			set
			{
				if ((this._slogan != value))
				{
					this.OnsloganChanging(value);
					this.SendPropertyChanging();
					this._slogan = value;
					this.SendPropertyChanged("slogan");
					this.OnsloganChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
